CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_CERVEZA`(P_NOMBRE VARCHAR(45), P_NEW_NOMBRE VARCHAR(45),
											P_NEW_PRECIO VARCHAR(45), P_NEW_CARACTERISTICAS VARCHAR(45), 
                                            P_NEW_ALCOHOL INT, P_NEW_AMARGO VARCHAR(45),
                                            P_NEW_TEMPERATURA VARCHAR(45), P_NEW_TIEMPOFERMENTACION VARCHAR(45),
                                            P_NEW_ID_ESTILO INT, P_NEW_ID_FABRICANTE INT,
                                            P_NEW_ID_CUERPO INT, P_NEW_ID_COLOR INT,
                                            P_NEW_ID_TIPO_FERMENTACION INT)

	UPDATE CERVEZA
SET NOMBRE = P_NEW_NOMBRE,
    PRECIO = P_NEW_PRECIO,
    CARACTERISTICAS = P_NEW_CARACTERISTICAS,
    ALCOHOL = P_NEW_ALCOHOL,
    AMARGO = P_NEW_AMARGO,
    TEMPERATURA = P_NEW_TEMPERATURA,
    TIEMPOFERMENTACION = P_NEW_TIEMPOFERMENTACION,
    ID_ESTILO = P_NEW_ID_ESTILO,
    ID_FABRICANTE = P_NEW_ID_FABRICANTE,
    ID_CUERPO = P_NEW_ID_CUERPO,
    ID_COLOR = P_NEW_ID_COLOR,
    ID_TIPO_FERMENTACION = P_NEW_ID_TIPO_FERMENTACION
WHERE NOMBRE = P_NOMBRE