CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_DISTRITO`(P_DESCRIPCION VARCHAR(45), P_NEW_DESCRIPCION VARCHAR(45),
								P_NEW_ID_CANTON INT(11))
BEGIN
	UPDATE DISTRITO
SET DESCRIPCION = P_NEW_DESCRIPCION,
	ID_CANTON = P_NEW_ANTON
    WHERE DESCRIPCION = P_DESCRIPCION;
COMMIT;
END