CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_PERSONA`(P_NOMBRE VARCHAR(45), P_APELLIDOUNO VARCHAR(45), 
												P_APELLIDODOS VARCHAR(45), P_CEDULA VARCHAR(45),
												P_NEW_NOMBRE VARCHAR(45), P_NEW_APELLIDOUNO VARCHAR(45),
												P_NEW_APELLIDODOS VARCHAR(45), P_NEW_CEDULA VARCHAR(45),
												P_NEW_FOTO VARCHAR(45), P_NEW_DISTRITO_ID INT(11), 
												P_NEW_USUARIO_ID INT(11))

  UPDATE PERSONA
SET NOMBRE = P_NEW_NOMBRE,
	APELLIDOUNO = P_NEW_APELLIDOUNO,
	APELLIDODOS = P_NEW_APELLIDODOS,
	CEDULA = P_NEW_CEDULA,
	FOTO = P_NEW_FOTO,
	ID_DISTRITO = P_NEW_DISTRITO_ID,
	ID_USUARIO = P_NEW_USUARIO_ID
WHERE NOMBRE = P_NOMBRE
	  AND APELLIDOUNO = P_APELLIDOUNO
	  AND APELLIDODOS = P_APELLIDODOS
	  AND CEDULA = P_CEDULA