CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_FAMILIA`(P_DESCRIPCION VARCHAR(45),
															P_NEW_DESCRIPCION VARCHAR(45))
BEGIN
	UPDATE FAMILIA
SET FAMILIA.DESCRIPCION = P_NEW_DESCRIPCION
    WHERE DESCRIPCION = P_DESCRIPCION;
COMMIT;
END