CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_ESTILO`(P_DESCRIPCION VARCHAR(45),
								P_NEW_DESCRIPCION VARCHAR(45),
								P_NEW_ID_FAMILIA INT(11))

	UPDATE ESTILO
SET DESCRIPCION = P_NEW_DESCRIPCION,
	ID_FAMILIA = P_NEW_FAMILIA
    WHERE DESCRIPCION = P_DESCRIPCION;
