CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_FABRICANTE`(P_DESCRIPCION VARCHAR(45),
									P_NEW_DESCRIPCION VARCHAR(45))

	UPDATE FABRICANTE
SET DESCRIPCION = P_NEW_DESCRIPCION
    WHERE DESCRIPCION = P_DESCRIPCION;
