CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_CUERPO`(P_DESCRIPCION VARCHAR(45),
									P_NEW_DESCRIPCION VARCHAR(45))

	UPDATE CUERPO
SET DESCRIPCION = P_NEW_DESCRIPCION
    WHERE DESCRIPCION = P_DESCRIPCION;
