CREATE DEFINER=`root`@`localhost` PROCEDURE `UPD_TIPO_FERMENTACION`(P_DESCRIPCION VARCHAR(45),
									P_NEW_DESCRIPCION VARCHAR(45))

	UPDATE TIPOFERMENTACION
SET DESCRIPCION = P_NEW_DESCRIPCION
    WHERE DESCRIPCION = P_DESCRIPCION;
